#!/usr/bin/python
import sys
file_name = sys.argv[1]
f = open(file_name)
count_table = {}
for line in f:
	if line in count_table:
		count_table[line] += 1
	else:
		count_table[line] = 1
keys = count_table.keys()
keys.sort()
for key in keys:
	sys.stdout.write('%s %s\n'%(key.strip(), count_table[key]))

